defmodule PerfectPaper.History.Comment do
  @moduledoc """
  One piece of referee-grade feedback on a manuscript: the quoted passage, the
  suggested change, and an explanation. A writer can leave it open, dismiss it,
  or mark it addressed.

  Comments may be AI-generated (`author_type: :ai`) or written by a human
  collaborator (`author_type: :user`, with `author_id` pointing to the user).
  Human comments may be top-level or threaded replies via `parent_id`
  (self-FK; deleting a parent nilifies `parent_id` on replies — replies survive).
  """
  use Ecto.Schema
  import Ecto.Changeset

  alias PerfectPaper.History.Session

  @type t :: %__MODULE__{}
  @type action :: :dismiss | :address

  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id
  schema "comments" do
    field :original_text, :string
    field :suggestion, :string
    field :explanation, :string
    field :category, :string
    field :status, Ecto.Enum, values: [:open, :dismissed, :addressed], default: :open
    field :position, :integer
    field :anchor_node_id, :string
    field :anchor_from, :integer
    field :anchor_to, :integer

    field :author_type, Ecto.Enum, values: [:ai, :user], default: :ai
    field :author_id, :binary_id
    field :body, :string
    field :parent_id, :binary_id

    belongs_to :session, Session

    timestamps(type: :utc_datetime_usec)
  end

  @doc "Builds a new comment generated by a review."
  @spec create_changeset(t(), map()) :: Ecto.Changeset.t()
  def create_changeset(comment, attrs) do
    comment
    |> cast(attrs, [
      :original_text,
      :suggestion,
      :explanation,
      :category,
      :position,
      :session_id,
      :anchor_node_id,
      :anchor_from,
      :anchor_to
    ])
    |> validate_required([:session_id])
    |> put_change(:author_type, :ai)
  end

  @doc "Builds a human collaborator comment (top-level or a reply via parent_id)."
  @spec author_changeset(t(), map()) :: Ecto.Changeset.t()
  def author_changeset(comment, attrs) do
    comment
    |> cast(attrs, [:session_id, :author_id, :body, :parent_id])
    |> validate_required([:session_id, :author_id, :body])
    |> put_change(:author_type, :user)
  end

  @doc "Moves a comment into the state implied by a writer's action."
  @spec apply_action_changeset(t(), action()) :: Ecto.Changeset.t()
  def apply_action_changeset(comment, :dismiss), do: change(comment, status: :dismissed)
  def apply_action_changeset(comment, :address), do: change(comment, status: :addressed)

  @doc "Reverts a comment to open when a writer undoes an action."
  @spec undo_action_changeset(t(), action()) :: Ecto.Changeset.t()
  def undo_action_changeset(comment, _action_type), do: change(comment, status: :open)
end
