defmodule PerfectPaperWeb.Api.Schemas do
  @moduledoc """
  OpenAPI schema modules for the PerfectPaper REST API.

  Each inner module uses the `OpenApiSpex.schema/1` macro and mirrors the exact
  field names and types returned by the JSON views (`history_json.ex`,
  `credit_json.ex`) and the error envelope in `fallback_controller.ex`.
  """

  alias OpenApiSpex.Schema

  defmodule Comment do
    @moduledoc "A single piece of referee-grade feedback on a manuscript passage."

    require OpenApiSpex

    OpenApiSpex.schema(%{
      title: "Comment",
      type: :object,
      description:
        "One comment generated by a PerfectPaper review: the quoted passage, " <>
          "a suggested rewrite, an explanation, a category tag, the writer's " <>
          "action status, and an ordinal position in the document. Human comments " <>
          "also carry author_type, author_id, body, and parent_id.",
      properties: %{
        id: %Schema{
          type: :string,
          format: :uuid,
          description: "UUID of the comment."
        },
        original_text: %Schema{
          type: :string,
          nullable: true,
          description: "The verbatim passage from the manuscript that this comment addresses."
        },
        suggestion: %Schema{
          type: :string,
          nullable: true,
          description: "The suggested replacement or improvement."
        },
        explanation: %Schema{
          type: :string,
          nullable: true,
          description: "Referee-grade rationale for the suggestion."
        },
        category: %Schema{
          type: :string,
          nullable: true,
          description: "Feedback category tag (e.g. \"clarity\", \"grammar\", \"structure\")."
        },
        status: %Schema{
          type: :string,
          enum: ["open", "dismissed", "addressed"],
          description:
            "The writer's current action on this comment. " <>
              "`open` — not yet acted on; " <>
              "`dismissed` — writer chose to ignore; " <>
              "`addressed` — writer has resolved the issue."
        },
        position: %Schema{
          type: :integer,
          nullable: true,
          description: "Ordinal position of the comment within the document (1-based)."
        },
        author_type: %Schema{
          type: :string,
          enum: ["ai", "user"],
          nullable: true,
          description: "`ai` for AI-generated feedback; `user` for human collaborator comments."
        },
        author_id: %Schema{
          type: :string,
          format: :uuid,
          nullable: true,
          description:
            "UUID of the user who wrote this comment. Present only when author_type is `user`."
        },
        body: %Schema{
          type: :string,
          nullable: true,
          description: "Free-text body of a human comment. Null for AI-generated comments."
        },
        parent_id: %Schema{
          type: :string,
          format: :uuid,
          nullable: true,
          description:
            "UUID of the parent comment when this is a threaded reply. Null for top-level comments."
        }
      },
      required: [:id, :status],
      example: %{
        id: "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        original_text: "The results shows a significant improvement.",
        suggestion: "The results show a significant improvement.",
        explanation:
          "Subject–verb agreement: \"results\" is plural and requires \"show\", not \"shows\".",
        category: "grammar",
        status: "open",
        position: 12,
        author_type: "ai",
        author_id: nil,
        body: nil,
        parent_id: nil
      }
    })
  end

  defmodule AddCommentRequest do
    @moduledoc "Request body for adding a human comment to a session."

    require OpenApiSpex

    OpenApiSpex.schema(%{
      title: "AddCommentRequest",
      type: :object,
      description:
        "Attributes for adding a human comment. Requires the commenter role on the session.",
      properties: %{
        body: %Schema{
          type: :string,
          description: "The comment text (required)."
        },
        parent_id: %Schema{
          type: :string,
          format: :uuid,
          nullable: true,
          description: "UUID of the parent comment to reply to. Must belong to the same session."
        }
      },
      required: [:body],
      example: %{
        body: "The methodology section needs more detail on the sampling procedure.",
        parent_id: nil
      }
    })
  end

  defmodule InvitationRequest do
    @moduledoc "Request body for inviting a collaborator to a session."

    require OpenApiSpex

    OpenApiSpex.schema(%{
      title: "InvitationRequest",
      type: :object,
      description:
        "Attributes for inviting a collaborator. Requires the :share permission on the session. " <>
          "Provide either `email` (a guest account is found or created and an invite email is sent) " <>
          "or `user_id` (an existing user; no email is sent). " <>
          "`role` defaults to `commenter` if omitted.",
      properties: %{
        email: %Schema{
          type: :string,
          format: :email,
          nullable: true,
          description: "Email of the recipient. A guest account is found or created."
        },
        user_id: %Schema{
          type: :string,
          format: :uuid,
          nullable: true,
          description: "UUID of an existing user to invite directly (no email sent)."
        },
        role: %Schema{
          type: :string,
          enum: ["viewer", "commenter", "editor"],
          description: "Role to grant. Defaults to `commenter`."
        }
      },
      example: %{
        email: "collaborator@university.edu",
        role: "commenter"
      }
    })
  end

  defmodule Invitation do
    @moduledoc "The result of a successful session invitation."

    require OpenApiSpex

    OpenApiSpex.schema(%{
      title: "Invitation",
      type: :object,
      description: "The user and role granted when an invitation succeeds.",
      properties: %{
        user_id: %Schema{
          type: :string,
          format: :uuid,
          description: "UUID of the invited/granted user."
        },
        role: %Schema{
          type: :string,
          enum: ["viewer", "commenter", "editor"],
          description: "The role granted to the user on the session."
        }
      },
      required: [:user_id, :role],
      example: %{
        user_id: "a1b2c3d4-e5f6-7a8b-9c0d-e1f2a3b4c5d6",
        role: "commenter"
      }
    })
  end

  defmodule InvitationResponse do
    @moduledoc "A single invitation result wrapped in the standard data envelope."

    require OpenApiSpex

    OpenApiSpex.schema(%{
      title: "InvitationResponse",
      type: :object,
      description: "An invitation result wrapped in the standard `{data: ...}` envelope.",
      properties: %{
        data: PerfectPaperWeb.Api.Schemas.Invitation
      },
      required: [:data]
    })
  end

  defmodule Session do
    @moduledoc "A proofreading session: one manuscript reviewed by PerfectPaper."

    require OpenApiSpex

    OpenApiSpex.schema(%{
      title: "Session",
      type: :object,
      description:
        "A proofreading session: one manuscript reviewed by PerfectPaper, carrying " <>
          "its processing status, overall feedback, sharing/viewed flags, and its comments.",
      properties: %{
        id: %Schema{
          type: :string,
          format: :uuid,
          description: "UUID of the session."
        },
        title: %Schema{
          type: :string,
          nullable: true,
          description: "Document title, if provided or detected."
        },
        processing_status: %Schema{
          type: :string,
          enum: ["pending", "converting", "analyzing", "complete", "failed"],
          description:
            "Current processing phase. " <>
              "`pending` — queued; " <>
              "`converting` — extracting text; " <>
              "`analyzing` — AI review in progress; " <>
              "`complete` — review finished; " <>
              "`failed` — processing error."
        },
        is_public: %Schema{
          type: :boolean,
          description: "Whether this session is publicly shareable."
        },
        viewed: %Schema{
          type: :boolean,
          description: "Whether the owner has opened the completed review."
        },
        overall_feedback: %Schema{
          type: :string,
          nullable: true,
          description:
            "A short summary paragraph of the overall review. " <>
              "Null until processing_status is `complete`."
        },
        comments: %Schema{
          type: :array,
          items: PerfectPaperWeb.Api.Schemas.Comment,
          description:
            "The list of comments generated for this session. " <>
              "Empty when the association is not loaded or the session is not yet complete."
        }
      },
      required: [:id, :processing_status, :is_public, :viewed],
      example: %{
        id: "1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d",
        title: "The Cognitive Load of Variable Naming in Student Programs",
        processing_status: "complete",
        is_public: false,
        viewed: true,
        overall_feedback:
          "The manuscript presents a well-structured study with clear methodology. " <>
            "Minor revisions to grammar and citation formatting are recommended.",
        comments: [
          %{
            id: "3fa85f64-5717-4562-b3fc-2c963f66afa6",
            original_text: "The results shows a significant improvement.",
            suggestion: "The results show a significant improvement.",
            explanation: "Subject–verb agreement: \"results\" is plural and requires \"show\".",
            category: "grammar",
            status: "open",
            position: 12
          }
        ]
      }
    })
  end

  defmodule CreditScore do
    @moduledoc "The current credit balance for the authenticated user."

    require OpenApiSpex

    OpenApiSpex.schema(%{
      title: "CreditScore",
      type: :object,
      description:
        "The authenticated user's current credit balance. " <>
          "Preserves the camelCase boundary convention from the original Refine API: " <>
          "`paidCreditsRemaining` and `previewCreditsRemaining`.",
      properties: %{
        paidCreditsRemaining: %Schema{
          type: :integer,
          description: "Credits purchased via a paid plan or top-up, available for full reviews."
        },
        previewCreditsRemaining: %Schema{
          type: :integer,
          description: "Complimentary preview credits available for trial/preview reviews."
        }
      },
      required: [:paidCreditsRemaining, :previewCreditsRemaining],
      example: %{
        paidCreditsRemaining: 42,
        previewCreditsRemaining: 3
      }
    })
  end

  defmodule Error do
    @moduledoc """
    The FastAPI-style error envelope used by FallbackController.

    `detail` is either a plain message string (for 400, 403, 404) or a list of
    `{loc, msg}` objects for 422 validation/changeset errors.
    """

    require OpenApiSpex

    OpenApiSpex.schema(%{
      title: "Error",
      type: :object,
      description:
        "FastAPI-style error envelope. " <>
          "`detail` is a message string for plain errors (400, 403, 404), " <>
          "or a list of `{loc, msg}` objects for validation errors (422).",
      properties: %{
        detail: %Schema{
          oneOf: [
            %Schema{
              type: :string,
              description: "Human-readable error message.",
              example: "Not found"
            },
            %Schema{
              type: :array,
              description: "List of field-level validation errors (422 only).",
              items: %Schema{
                type: :object,
                properties: %{
                  loc: %Schema{
                    type: :array,
                    items: %Schema{type: :string},
                    description: "Location path to the invalid field, e.g. [\"body\", \"email\"]."
                  },
                  msg: %Schema{
                    type: :string,
                    description: "Human-readable description of the validation failure."
                  }
                },
                required: [:loc, :msg]
              }
            }
          ]
        }
      },
      required: [:detail],
      example: %{detail: "Not found"}
    })
  end

  defmodule LoginRequest do
    @moduledoc "Credentials for the session log-in endpoint."

    require OpenApiSpex

    OpenApiSpex.schema(%{
      title: "LoginRequest",
      type: :object,
      description: "Credentials submitted to the session log-in endpoint.",
      properties: %{
        email: %Schema{
          type: :string,
          format: :email,
          description: "The user's registered email address."
        },
        password: %Schema{
          type: :string,
          format: :password,
          description: "The user's password."
        }
      },
      required: [:email, :password],
      example: %{
        email: "researcher@university.edu",
        password: "correct-horse-battery-staple"
      }
    })
  end

  defmodule WebhookEndpoint do
    @moduledoc "A webhook endpoint registered by an org admin."

    require OpenApiSpex

    OpenApiSpex.schema(%{
      title: "WebhookEndpoint",
      type: :object,
      description:
        "An org-scoped webhook endpoint. PerfectPaper delivers matching events " <>
          "to `url` as signed HTTP POSTs. The `secret` field is only present " <>
          "immediately after creation or a secret rotation.",
      properties: %{
        id: %Schema{
          type: :string,
          format: :uuid,
          description: "UUID of the endpoint."
        },
        url: %Schema{
          type: :string,
          format: :uri,
          description: "HTTPS URL to which events are delivered."
        },
        event_types: %Schema{
          type: :array,
          items: %Schema{type: :string},
          description: "List of event type strings this endpoint subscribes to."
        },
        description: %Schema{
          type: :string,
          nullable: true,
          description: "Optional human-readable label for this endpoint."
        },
        active: %Schema{
          type: :boolean,
          description: "Whether the endpoint receives deliveries."
        },
        inserted_at: %Schema{
          type: :string,
          format: :"date-time",
          description: "ISO 8601 timestamp when the endpoint was created."
        },
        secret: %Schema{
          type: :string,
          nullable: true,
          description:
            "HMAC signing secret. Returned ONLY on create and rotate-secret — " <>
              "store it immediately; it cannot be retrieved afterwards."
        }
      },
      required: [:id, :url, :event_types, :active, :inserted_at],
      example: %{
        id: "a1b2c3d4-e5f6-7a8b-9c0d-e1f2a3b4c5d6",
        url: "https://hooks.example.com/perfectpaper",
        event_types: ["session.completed"],
        description: "Production delivery endpoint",
        active: true,
        inserted_at: "2026-01-15T10:00:00Z"
      }
    })
  end

  defmodule WebhookEndpointRequest do
    @moduledoc "Request body for creating or updating a webhook endpoint."

    require OpenApiSpex

    OpenApiSpex.schema(%{
      title: "WebhookEndpointRequest",
      type: :object,
      description: "Attributes for creating or updating a webhook endpoint.",
      properties: %{
        url: %Schema{
          type: :string,
          format: :uri,
          description: "HTTPS destination URL for event delivery."
        },
        event_types: %Schema{
          type: :array,
          items: %Schema{type: :string},
          description: "Event type strings to subscribe to."
        },
        description: %Schema{
          type: :string,
          nullable: true,
          description: "Optional human-readable label."
        },
        active: %Schema{
          type: :boolean,
          description: "Whether the endpoint should receive deliveries."
        }
      },
      example: %{
        url: "https://hooks.example.com/perfectpaper",
        event_types: ["session.completed"],
        description: "Production endpoint",
        active: true
      }
    })
  end

  defmodule WebhookEndpointResponse do
    @moduledoc "A single webhook endpoint wrapped in the standard data envelope."

    require OpenApiSpex

    OpenApiSpex.schema(%{
      title: "WebhookEndpointResponse",
      type: :object,
      description: "A single webhook endpoint wrapped in the `{data: ...}` envelope.",
      properties: %{
        data: PerfectPaperWeb.Api.Schemas.WebhookEndpoint
      },
      required: [:data]
    })
  end

  defmodule WebhookEndpointListResponse do
    @moduledoc "A list of webhook endpoints wrapped in the standard data envelope."

    require OpenApiSpex

    OpenApiSpex.schema(%{
      title: "WebhookEndpointListResponse",
      type: :object,
      description: "A list of webhook endpoints wrapped in the `{data: [...]}` envelope.",
      properties: %{
        data: %Schema{
          type: :array,
          items: PerfectPaperWeb.Api.Schemas.WebhookEndpoint
        }
      },
      required: [:data]
    })
  end

  defmodule WebhookDelivery do
    @moduledoc "A webhook delivery log entry."

    require OpenApiSpex

    OpenApiSpex.schema(%{
      title: "WebhookDelivery",
      type: :object,
      description:
        "A single delivery attempt record for a webhook endpoint. " <>
          "Tracks HTTP response status, attempt count, and outcome.",
      properties: %{
        id: %Schema{
          type: :string,
          format: :uuid,
          description: "UUID of the delivery record."
        },
        event_type: %Schema{
          type: :string,
          description: "The event type string that triggered this delivery."
        },
        status: %Schema{
          type: :string,
          enum: ["pending", "delivered", "failed"],
          description:
            "`pending` — awaiting dispatch; " <>
              "`delivered` — endpoint responded 2xx; " <>
              "`failed` — all attempts exhausted."
        },
        attempts: %Schema{
          type: :integer,
          description: "Number of delivery attempts made so far."
        },
        response_status: %Schema{
          type: :integer,
          nullable: true,
          description: "HTTP response status code from the most recent attempt."
        },
        inserted_at: %Schema{
          type: :string,
          format: :"date-time",
          description: "ISO 8601 timestamp when the delivery record was created."
        },
        delivered_at: %Schema{
          type: :string,
          format: :"date-time",
          nullable: true,
          description: "ISO 8601 timestamp of successful delivery, or null."
        }
      },
      required: [:id, :event_type, :status, :attempts, :inserted_at],
      example: %{
        id: "d1e2f3a4-b5c6-7d8e-9f0a-b1c2d3e4f5a6",
        event_type: "session.completed",
        status: "delivered",
        attempts: 1,
        response_status: 200,
        inserted_at: "2026-01-15T10:05:00Z",
        delivered_at: "2026-01-15T10:05:01Z"
      }
    })
  end

  defmodule WebhookDeliveryListResponse do
    @moduledoc "A list of webhook deliveries wrapped in the standard data envelope."

    require OpenApiSpex

    OpenApiSpex.schema(%{
      title: "WebhookDeliveryListResponse",
      type: :object,
      description:
        "A list of delivery log entries for a webhook endpoint, " <>
          "wrapped in the `{data: [...]}` envelope.",
      properties: %{
        data: %Schema{
          type: :array,
          items: PerfectPaperWeb.Api.Schemas.WebhookDelivery
        }
      },
      required: [:data]
    })
  end

  defmodule SessionListResponse do
    @moduledoc "Paginated list of sessions wrapped in the standard `data` envelope."

    require OpenApiSpex

    OpenApiSpex.schema(%{
      title: "SessionListResponse",
      type: :object,
      description: "A list of sessions wrapped in the standard `{data: [...]}` envelope.",
      properties: %{
        data: %Schema{
          type: :array,
          items: PerfectPaperWeb.Api.Schemas.Session
        }
      },
      required: [:data]
    })
  end

  defmodule SessionResponse do
    @moduledoc "A single session wrapped in the standard `data` envelope."

    require OpenApiSpex

    OpenApiSpex.schema(%{
      title: "SessionResponse",
      type: :object,
      description: "A single session wrapped in the standard `{data: ...}` envelope.",
      properties: %{
        data: PerfectPaperWeb.Api.Schemas.Session
      },
      required: [:data]
    })
  end

  defmodule CommentResponse do
    @moduledoc "A single comment wrapped in the standard `data` envelope."

    require OpenApiSpex

    OpenApiSpex.schema(%{
      title: "CommentResponse",
      type: :object,
      description: "A single comment wrapped in the standard `{data: ...}` envelope.",
      properties: %{
        data: PerfectPaperWeb.Api.Schemas.Comment
      },
      required: [:data]
    })
  end

  defmodule SsoConfig do
    @moduledoc "An org's enterprise SSO configuration, with secrets REDACTED."

    require OpenApiSpex

    OpenApiSpex.schema(%{
      title: "SsoConfig",
      type: :object,
      description:
        "An organization's enterprise SSO (OIDC / SAML) configuration. " <>
          "Secret material — the OIDC client secret and the SAML IdP certificate — " <>
          "is NEVER returned. Instead, boolean `*_set` flags indicate whether each " <>
          "secret is currently stored.",
      properties: %{
        configured: %Schema{
          type: :boolean,
          description:
            "`false` when the org has no SSO configuration yet (all other fields null)."
        },
        protocol: %Schema{
          type: :string,
          enum: ["oidc", "saml"],
          nullable: true,
          description: "The SSO protocol in use."
        },
        email_domain: %Schema{
          type: :string,
          nullable: true,
          description: "The corporate email domain that routes login to this IdP."
        },
        domain_verified: %Schema{
          type: :boolean,
          description: "Whether the email domain has been verified."
        },
        enabled: %Schema{
          type: :boolean,
          description: "Whether SSO is active. Can only be enabled once the domain is verified."
        },
        oidc_tenant_id: %Schema{
          type: :string,
          nullable: true,
          description: "OIDC tenant id (Entra directory id)."
        },
        oidc_client_id: %Schema{
          type: :string,
          nullable: true,
          description: "OIDC application/client id."
        },
        oidc_client_secret_set: %Schema{
          type: :boolean,
          description:
            "Whether an OIDC client secret is stored. The secret itself is never returned."
        },
        saml_idp_entity_id: %Schema{
          type: :string,
          nullable: true,
          description: "SAML IdP entity id."
        },
        saml_idp_sso_url: %Schema{
          type: :string,
          nullable: true,
          description: "SAML IdP single sign-on URL."
        },
        saml_idp_cert_set: %Schema{
          type: :boolean,
          description:
            "Whether a SAML IdP signing certificate is stored. The certificate itself is never returned."
        },
        saml_sp_entity_id: %Schema{
          type: :string,
          nullable: true,
          description: "SAML SP (PerfectPaper) entity id."
        }
      },
      required: [:configured, :domain_verified, :enabled],
      example: %{
        configured: true,
        protocol: "oidc",
        email_domain: "acme.test",
        domain_verified: true,
        enabled: false,
        oidc_tenant_id: "tenant-abc",
        oidc_client_id: "client-123",
        oidc_client_secret_set: true,
        saml_idp_entity_id: nil,
        saml_idp_sso_url: nil,
        saml_idp_cert_set: false,
        saml_sp_entity_id: nil
      }
    })
  end

  defmodule SsoConfigResponse do
    @moduledoc "An SSO config (secrets redacted) wrapped in the standard data envelope."

    require OpenApiSpex

    OpenApiSpex.schema(%{
      title: "SsoConfigResponse",
      type: :object,
      description: "A redacted SSO config wrapped in the standard `{data: ...}` envelope.",
      properties: %{
        data: PerfectPaperWeb.Api.Schemas.SsoConfig
      },
      required: [:data]
    })
  end

  defmodule SsoConfigRequest do
    @moduledoc "Request body for creating or updating an org's SSO configuration."

    require OpenApiSpex

    OpenApiSpex.schema(%{
      title: "SsoConfigRequest",
      type: :object,
      description:
        "SSO credential attributes. Provide OIDC fields when `protocol` is `oidc`, " <>
          "or SAML fields when `protocol` is `saml`. Setting any security field on an " <>
          "already verified+enabled config automatically revokes verification and disables SSO.",
      properties: %{
        protocol: %Schema{
          type: :string,
          enum: ["oidc", "saml"],
          description: "The SSO protocol to configure."
        },
        email_domain: %Schema{
          type: :string,
          description: "The corporate email domain (must not be a public free-email provider)."
        },
        oidc_tenant_id: %Schema{type: :string, nullable: true, description: "OIDC tenant id."},
        oidc_client_id: %Schema{type: :string, nullable: true, description: "OIDC client id."},
        oidc_client_secret: %Schema{
          type: :string,
          format: :password,
          nullable: true,
          description: "OIDC client secret. Write-only — never returned in any response."
        },
        saml_idp_entity_id: %Schema{
          type: :string,
          nullable: true,
          description: "SAML IdP entity id."
        },
        saml_idp_sso_url: %Schema{type: :string, nullable: true, description: "SAML IdP SSO URL."},
        saml_idp_cert: %Schema{
          type: :string,
          nullable: true,
          description:
            "SAML IdP signing certificate. Write-only — never returned in any response."
        },
        saml_sp_entity_id: %Schema{
          type: :string,
          nullable: true,
          description: "SAML SP entity id."
        }
      },
      required: [:protocol, :email_domain],
      example: %{
        protocol: "oidc",
        email_domain: "acme.test",
        oidc_tenant_id: "tenant-abc",
        oidc_client_id: "client-123",
        oidc_client_secret: "super-secret"
      }
    })
  end

  defmodule SsoEnableRequest do
    @moduledoc "Request body for enabling or disabling an org's SSO."

    require OpenApiSpex

    OpenApiSpex.schema(%{
      title: "SsoEnableRequest",
      type: :object,
      description: "Toggle SSO on or off. Enabling requires the domain to be verified first.",
      properties: %{
        enabled: %Schema{type: :boolean, description: "Whether SSO should be active."}
      },
      required: [:enabled],
      example: %{enabled: true}
    })
  end

  defmodule BillingContract do
    @moduledoc "An org's enterprise seat-based billing contract + live seat usage."

    require OpenApiSpex

    OpenApiSpex.schema(%{
      title: "BillingContract",
      type: :object,
      description: "Seat-based contract with live seat usage and pool status.",
      properties: %{
        id: %Schema{type: :string},
        status: %Schema{type: :string, enum: ["draft", "active", "expired", "canceled"]},
        seats: %Schema{type: :integer, description: "Contracted seats."},
        seats_used: %Schema{type: :integer, description: "Current active members."},
        seat_overage: %Schema{type: :integer, description: "max(0, used - contracted)."},
        price_per_seat_cents: %Schema{type: :integer},
        per_seat_credits: %Schema{type: :integer},
        interval: %Schema{type: :string, enum: ["monthly", "annual"]},
        term_start: %Schema{type: :string, format: :date},
        term_end: %Schema{type: :string, format: :date},
        po_number: %Schema{type: :string, nullable: true},
        net_terms_days: %Schema{type: :integer},
        credit_pool: %Schema{
          type: :integer,
          description: "Org credit pool (may be negative under a contract)."
        }
      },
      example: %{
        id: "…",
        status: "active",
        seats: 10,
        seats_used: 12,
        seat_overage: 2,
        price_per_seat_cents: 5000,
        per_seat_credits: 100,
        interval: "monthly",
        term_start: "2026-06-01",
        term_end: "2027-06-01",
        po_number: "PO-42",
        net_terms_days: 30,
        credit_pool: 1200
      }
    })
  end

  defmodule BillingContractRequest do
    @moduledoc "Request body to create/edit a draft contract (platform-admin only)."

    require OpenApiSpex

    OpenApiSpex.schema(%{
      title: "BillingContractRequest",
      type: :object,
      description: "Draft contract terms. Amounts are integer cents.",
      properties: %{
        seats: %Schema{type: :integer},
        price_per_seat_cents: %Schema{type: :integer},
        per_seat_credits: %Schema{type: :integer},
        interval: %Schema{type: :string, enum: ["monthly", "annual"]},
        term_start: %Schema{type: :string, format: :date},
        term_end: %Schema{type: :string, format: :date},
        po_number: %Schema{type: :string}
      },
      required: [:seats, :term_start, :term_end],
      example: %{
        seats: 10,
        price_per_seat_cents: 5000,
        per_seat_credits: 100,
        interval: "monthly",
        term_start: "2026-06-01",
        term_end: "2027-06-01",
        po_number: "PO-42"
      }
    })
  end

  defmodule BillingInvoice do
    @moduledoc "An internal AR invoice for a contract period."

    require OpenApiSpex

    OpenApiSpex.schema(%{
      title: "BillingInvoice",
      type: :object,
      properties: %{
        id: %Schema{type: :string},
        number: %Schema{type: :string, description: "Non-enumerable INV-YYYYMM-<rand>."},
        period_start: %Schema{type: :string, format: :date},
        period_end: %Schema{type: :string, format: :date},
        seats_billed: %Schema{type: :integer},
        seat_overage: %Schema{type: :integer},
        amount_cents: %Schema{type: :integer},
        status: %Schema{type: :string, enum: ["issued", "paid", "overdue", "void"]},
        issued_at: %Schema{type: :string, format: :"date-time"},
        due_at: %Schema{type: :string, format: :"date-time"},
        paid_at: %Schema{type: :string, format: :"date-time", nullable: true}
      },
      example: %{
        id: "…",
        number: "INV-202606-A2B3C4D5",
        period_start: "2026-06-01",
        period_end: "2026-07-01",
        seats_billed: 10,
        seat_overage: 2,
        amount_cents: 60000,
        status: "issued",
        issued_at: "2026-06-01T00:00:00Z",
        due_at: "2026-07-01T00:00:00Z",
        paid_at: nil
      }
    })
  end
end
